### ISSUE TITLE
error: failed to run custom build command for `ffmpeg-sys-next v4.4.0`

### ISSUE THREAD

**Issue by AmirMehr** [dceddia/ffmpeg-cpal-play-audio#1]
I am new to Rust and in audio, it throws error like this when I want to build:
```
error: failed to run custom build command for `ffmpeg-sys-next v4.4.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `C:\Users\OrginWeb\Downloads\ffmpeg-cpal-play-audio-main\target\debug\build\ffmpeg-sys-next-299154bd8a0ec61d\build-script-build` (exit code: 101)
  --- stdout
  Could not find ffmpeg with vcpkg: Could not find Vcpkg tree: No vcpkg installation found. Set the VCPKG_ROOT environment variable or run 'vcpkg integrate install'
  cargo:rerun-if-env-changed=LIBAVUTIL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at C:\Users\OrginWeb\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ffmpeg-sys-next-4.4.0\build.rs:701:14:
  called `Result::unwrap()` on an `Err` value: Command { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"libavutil\"", cause: Error { kind: NotFound, message: "program not found" } }
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:665
     1: core::panicking::panic_fmt
               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\panicking.rs:74
     2: core::result::unwrap_failed
               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\result.rs:1679
     3: build_script_build::link_to_libraries::{{closure}}
     4: core::fmt::Arguments::new_v1_formatted
     5: std::ffi::os_str::OsStr::to_str
     6: std::rt::lang_start
     7: std::rt::lang_start_internal::closure$2
               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\rt.rs:141
     8: std::panicking::try::do_call
               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:557
     9: std::panicking::try
               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:521
    10: std::panic::catch_unwind
               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panic.rs:350
    11: std::rt::lang_start_internal
               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\rt.rs:141
    12: std::rt::lang_start
    13: main
    14: invoke_main
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    15: __scrt_common_main_seh
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    16: BaseThreadInitThunk
    17: RtlUserThreadStart
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

 *  The terminal process "C:\Users\OrginWeb\.cargo\bin\cargo.exe 'run', '--package', 'ffmpeg-cpal-play-audio', '--bin', 'ffmpeg-cpal-play-audio'" terminated with exit code: 101. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by dceddia** [comment]
I'm not sure but it looks like something to do with `vcpkg`. I've never tried to run this on Windows though.
